services:
  api:
    build:
      context: ..
      dockerfile: infra/dockerfiles/api/Dockerfile.dev
    volumes:
      - ../packages/api/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build:
      context: ..
      dockerfile: infra/dockerfiles/bot/Dockerfile.dev
    volumes:
      - ../packages/bot/src:/app/packages/bot/src
      - ../packages/shared/src:/app/packages/bot/src/shared

  web:
    build:
      context: ..
      dockerfile: infra/dockerfiles/web/Dockerfile.dev
    volumes:
      - ../packages/web/src:/app/packages/web/src
      - ../packages/web/public:/app/packages/web/public
